# ===================================================================
# CONEXIÓN A BASE DE DATOS - RAILWAY (RED PRIVADA)
# ===================================================================
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ahjVyiLsAHnaelfFgCURyHxEQrOMQman
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Puerto obligatorio para el contenedor de Railway
server.port=${PORT:8080}

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Pool de conexiones (evita que se cuelgue esperando indefinidamente)
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.initialization-fail-timeout=0